services:
  front-end:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    depends_on:
      - back-end

  back-end:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    ports:
      - "4220:4220"
      - "4250:4250"
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: somepassword

networks:
  app-network:
    driver: bridge
